package com.docassistant.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * JPA entity representing an uploaded document and its processing artefacts.
 *
 * <p>Stores the original filename, extracted full text, JSON-serialized text
 * chunks (used for contextual retrieval during Q&amp;A), page count, processing
 * status, and timestamps.</p>
 *
 * <p>The {@code id} is a server-generated UUID ensuring uniqueness across
 * distributed deployments without requiring database-level sequence coordination.</p>
 */
@Entity
@Table(name = "documents")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Document {

    /** Unique identifier — UUID generated by Hibernate. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /** ID of the user who owns this document. */
    @Column(name = "user_id")
    private String userId;

    /** Original filename as uploaded by the client. */
    @Column(nullable = false)
    private String filename;

    /** File size in bytes. */
    private Long fileSize;

    /** Number of pages extracted from the PDF. */
    private Integer pageCount;

    /** Full extracted plain-text content of the document. */
    @Column(columnDefinition = "TEXT")
    private String extractedText;

    /**
     * JSON-serialized array of text chunks used for contextual retrieval.
     * Each chunk is a semantically meaningful segment of the document.
     */
    @Column(columnDefinition = "TEXT")
    private String textChunksJson;

    /** Current processing status of the document. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private DocumentStatus status;

    /** Timestamp when the document was uploaded. */
    @Column(nullable = false)
    private LocalDateTime uploadedAt;

    /** Human-readable error message if processing failed. */
    @Column(columnDefinition = "TEXT")
    private String errorMessage;

    /** Auto-generated brief summary of the document. */
    @Column(columnDefinition = "TEXT")
    private String summary;

    /**
     * Sets the upload timestamp to now before the first persist.
     */
    @PrePersist
    protected void onCreate() {
        if (uploadedAt == null) {
            uploadedAt = LocalDateTime.now();
        }
    }
}
